### ISSUE TITLE
Basic web-app with micro-services

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/oSPARC_Test#2]
## Basic
- simple web-ui 
- simple service/s implemented in different languages but exposing a REST api
- click button in web-ui and consume these services REST apis
- display some response in web-ui

## Improvement +1
 - deploy and orchestrate services in different virtual machines

## Improvement +2
 - implement complete RESTApi

**Comment by mguidon** [comment]
- Connect to react-ui
